name: CI/CD Pipeline for React Frontend

on:
  push:
    branches:
      - main  # Only trigger on changes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set CI to false to prevent warnings from blocking the build
      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV

      # Install Node.js and dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use a suitable Node.js version for your project

      - name: Install dependencies
        run: npm install

      # Build the React app
      - name: Build the React app
        run: npm run build

      # Set up Docker CLI
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/attendance_frontend:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # This job runs after the build-and-push job

    steps:
      # SSH into the server to deploy the Docker container
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/attendance_frontend:latest

            # Stop and remove any running container with the same name
            docker stop attendance_frontend || true
            docker rm attendance_frontend || true

            # Kill the process using port 3000, if any
            PORT_IN_USE=$(lsof -t -i :3000 || true)
            if [ "$PORT_IN_USE" ]; then
              echo "Port 3000 is in use. Stopping process with PID $PORT_IN_USE..."
              kill -9 $PORT_IN_USE || true
            fi

            # Start the new container
            echo "Starting new container..."
            docker run -d --name attendance_frontend -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/attendance_frontend:latest
